Document: msdl
Title: Debian msdl Manual
Author: <insert document author here>
Abstract: This manual describes what msdl is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/msdl/msdl.sgml.gz

Format: postscript
Files: /usr/share/doc/msdl/msdl.ps.gz

Format: text
Files: /usr/share/doc/msdl/msdl.text.gz

Format: HTML
Index: /usr/share/doc/msdl/html/index.html
Files: /usr/share/doc/msdl/html/*.html
