Document: tvdownloader
Title: Debian tvdownloader Manual
Author: <insert document author here>
Abstract: This manual describes what tvdownloader is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/tvdownloader/tvdownloader.sgml.gz

Format: postscript
Files: /usr/share/doc/tvdownloader/tvdownloader.ps.gz

Format: text
Files: /usr/share/doc/tvdownloader/tvdownloader.text.gz

Format: HTML
Index: /usr/share/doc/tvdownloader/html/index.html
Files: /usr/share/doc/tvdownloader/html/*.html
